debug: true
# bot 设置
bot_config:
  # 最高权限管理QQ号 高过 群主/管理员
  super_admin: [2939599299]
  # 对bot的称呼
  bot_name: ["小白"]

# 其他api设置
ett:
  uin: ""
  pwd: ""
  # 冷却时间 单位: 秒
  cooldown: 2
  #api 超时时间 单位: 秒
  timeout:
setu:
  # 色图自动撤回时间 单位: 秒
  recall_time: 60
  # 色图是否保存本地
  whether_to_save_locally: false
# https://apexlegendsapi.com/#introduction
apex_api: "f3ddeb115eaf5b86cae23ee8279cd5a6"
